export const shoeData = {
  styles: [
    {
      id: "1",
      name: "Athletic/Sneakers",
      description: "Shoes designed for sports and active lifestyles",
    },
    {
      id: "2",
      name: "Casual",
      description: "Everyday comfortable shoes",
    },
    {
      id: "3",
      name: "Slippers",
      description: "Soft, comfortable indoor footwear",
    },
    {
      id: "4",
      name: "Dress",
      description: "Formal footwear for professional or special occasions",
    },
  ],
  conditions: [
    {
      id: "1",
      name: "Plantar Fasciitis",
      description: "Shoes with proper arch support and heel cushioning",
    },
    {
      id: "2",
      name: "Diabetic-Friendly",
      description: "Non-binding footwear with extra depth for diabetic feet",
    },
    {
      id: "3",
      name: "Wide Foot",
      description: "Shoes with wider toe box for comfort",
    },
    {
      id: "4",
      name: "Foot-Pain",
      description: "Cushioned shoes designed to minimize general foot pain",
    },
    {
      id: "5",
      name: "Orthopedic",
      description: "Shoes designed to support and align the foot, ankle, and lower limbs",
    },
  ],
  brands: [
    {
      id: "1",
      name: "OrthoFeet",
      description: "Manufacturer of therapeutic footwear for various foot conditions",
    },
    {
      id: "2",
      name: "Dr. Comfort",
      description: "Specializes in diabetic and therapeutic footwear",
    },
    {
      id: "3",
      name: "Skechers",
      description: "Casual and athletic footwear brand",
    },
    {
      id: "4",
      name: "Brooks",
      description: "Performance running shoes",
    },
    {
      id: "5",
      name: "Teva",
      description: "Outdoor and adventure sandals and shoes",
    },
    {
      id: "6",
      name: "Crocs",
      description: "Casual foam clogs and footwear",
    },
    {
      id: "7",
      name: "Birkenstock",
      description: "Known for contoured cork footbeds and sandals",
    },
    {
      id: "8",
      name: "Flux",
      description: "Modern footwear with adaptive features",
    },
    {
      id: "9",
      name: "Vionic",
      description: "Shoes with built-in orthotic technology",
    },
    {
      id: "10",
      name: "Propét",
      description: "Therapeutic and orthopedic footwear",
    },
    {
      id: "11",
      name: "Time and Tru",
      description: "Affordable fashion footwear",
    },
    {
      id: "12",
      name: "Apt. 9",
      description: "Fashion footwear brand",
    },
  ],
  shoes: [
    {
      id: "1",
      name: "OrthoFeet Tilos Hands-Free",
      brand_id: "1",
      condition_id: "1",
      style_id: "2",
      gender: "Male",
      price: 160.0,
      rating: 4.25,
      product_url: "https://www.orthofeet.com/products/tilos-hands-free-black-black",
      image_url: "https://www.orthofeet.com/cdn/shop/files/20022-Tilos-Navy-Blue-Angle.jpg?v=1733432571&width=1200",
      description:
        "It's ready, set, go & for all day comfort in modern sneaker style. Our patented hands-free, slip-on technology means no time bent over to tie the laces. Water-repellent stretch uppers take the pressure off every curve and bump of your feet, while the advanced, customizable Ortho-Cushion System takes the pain out of every step, to always keep your healthy mobility on track.",
    },
    {
      id: "2",
      name: "OrthoFeet Kita Hands-Free",
      brand_id: "1",
      condition_id: "1",
      style_id: "2",
      gender: "Female",
      price: 125.0,
      rating: 4.26,
      product_url: "https://www.orthofeet.com/products/kita-hands-free-black-black",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/80016-Kita-Black-Black-Angle_68449432-c6bc-44b3-bba7-ad28050d39a3.jpg?v=1702513025&width=1200",
      description:
        "Kita's clean sporty design features our revolutionary hands-free slip-on technology. Tie the laces once, then never bend over to tie them again & just step in, without worrying about them slipping off when walking. From the water-repellant stretchable fabric uppers to the Ortho-Cushion System, Kita changes the game for mobility, support and comfort.",
    },
    {
      id: "3",
      name: "OrthoFeet Fairway Hands-Free Golf",
      brand_id: "1",
      condition_id: "1",
      style_id: "1",
      gender: "Male",
      price: 129.99,
      rating: 4.39,
      product_url: "https://www.orthofeet.com/products/fairway-hands-free-blue-white-gray",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/28003-Fairway-HF-Golf-White-Blue-Gray-Angle_1242x1674.jpg?v=1737477136",
      description:
        "Put your comfort to the fore and enjoy every round more with advanced support, heel-to-toe impact absorption and the easy walking stability of the Ortho-Cushion System. Our patented hands-free design offers slip-on ease and secure footing, with a golf-spike tread for traction on uneven surfaces.",
    },
    {
      id: "4",
      name: "OrthoFeet Ace Pickleball Hands-Free",
      brand_id: "1",
      condition_id: "1",
      style_id: "1",
      gender: "Female",
      price: 124.99,
      rating: 4.39,
      product_url: "https://www.orthofeet.com/products/ace-pickleball-hands-free-white-gray",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/88002-Ace-Pickle-Ball-White-Gray-Angle_1242x1674.jpg?v=1729714647",
      description:
        "More game, less pain. Purpose-built for pickleball, Ace dodges joint strain and pressure points with advanced heel-to-toe cushioning, roomy fit and superior body-aligning support. The patented hands-free design slips-on easily and stays secure.",
    },
    {
      id: "5",
      name: "OrthoFeet Nira Hands-Free",
      brand_id: "1",
      condition_id: "1",
      style_id: "1",
      gender: "Female",
      price: 165.0,
      rating: 4.07,
      product_url: "https://www.orthofeet.com/products/nira-hands-free-black",
      image_url: "https://www.orthofeet.com/cdn/shop/files/80031-Nira-Green-Blue-Angle.jpg?v=1740149728&width=1200",
      description:
        "Nira takes your active, pain-free comfort to the next level in modern sneaker style. With our patented hands-free technology, you can skip the laces. Just step-in and go! The water-repellant stretch upper keeps pressure off sensitive areas, while an advanced orthotic sole design disperses walking impact, to get you happily through every day's finish line.",
    },
    {
      id: "6",
      name: "OrthoFeet Relay",
      brand_id: "1",
      condition_id: "1",
      style_id: "1",
      gender: "Female",
      price: 124.99,
      rating: 4.31,
      product_url: "https://www.orthofeet.com/products/relay",
      image_url: "https://m.media-amazon.com/images/I/61mJ8tY1HdL._AC_SL1400_.jpg",
      description:
        "Get ready for podiatrist-recommended comfort that's born to run. From the lightweight breathable nylon upper to the stable, high traction outsole, Relay keeps your mobility in the lead. Leave pain behind with a heel-to-toe max cushioned sole and a near custom fit, while the Ortho-Cushion System offloads pressure and aligns ergonomic support for every stride.",
    },
    {
      id: "7",
      name: "Dr. Comfort William X Diabetic Shoes",
      brand_id: "2",
      condition_id: "2",
      style_id: "2",
      gender: "Male",
      price: 128.0,
      rating: 4.3,
      product_url: "https://www.amazon.com/Dr-Comfort-William-X-Double-Diabetic/dp/B00IOT5GIU",
      image_url: "https://m.media-amazon.com/images/I/71rZ2dHT-mL._AC_SY695_.jpg",
      description:
        "Men's Double Depth Casual Shoe – Designed for comfort and support, this sleek casual shoe features extra depth to accommodate a variety of foot needs. Double Depth Construction – Provides additional space to accommodate severe edema, internal braces, and AFOs.",
    },
    {
      id: "8",
      name: "Skechers Go Walk Joy Sneaker",
      brand_id: "3",
      condition_id: "2",
      style_id: "2",
      gender: "Female",
      price: 65.0,
      rating: 4.4,
      product_url: "https://www.skechers.com/go-walk-joy---aurora/124637_BBK.html",
      image_url:
        "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwc6c2d4f1/images/large/124637_NVW.jpg?sw=1600",
      description:
        "If you're on a tight budget, check out Skechers Go Walk Joy Sneakers. These shoes slip on and off easily, and are extremely comfortable to wear, thanks to their plush cushioning.",
    },
    {
      id: "9",
      name: "Dr. Comfort Refresh X Blue Diabetic Shoes",
      brand_id: "2",
      condition_id: "2",
      style_id: "2",
      gender: "Female",
      price: 162.5,
      rating: 4.1,
      product_url: "https://www.drcomfort.com/refresh-x",
      image_url:
        "https://www.drcomfort.com/media/catalog/product/cache/2f72bf07d911f86e77d93eed57c55d3a/r/e/refresh-x-blue-2950-3-4_47.jpg",
      description:
        "Have swollen feet? You might want to give these Dr. Comfort Refresh X Blue Diabetic shoes a try. These sneakers come in three widths: regular, wide, and X-wide, and sizes 4 through 12. We're fans of the seamless inside lining, which helps reduce unnecessary rubbing of toes.",
    },
    {
      id: "10",
      name: "OrthoFeet Tilos Hands-Free",
      brand_id: "1",
      condition_id: "2",
      style_id: "2",
      gender: "Male",
      price: 160.0,
      rating: 4.25,
      product_url: "https://www.orthofeet.com/products/tilos-hands-free-black-black",
      image_url: "https://www.orthofeet.com/cdn/shop/files/20022-Tilos-Navy-Blue-Angle.jpg?v=1733432571&width=1200",
      description:
        "It's ready, set, go & for all day comfort in modern sneaker style. Our patented hands-free, slip-on technology means no time bent over to tie the laces. Water-repellent stretch uppers take the pressure off every curve and bump of your feet, while the advanced, customizable Ortho-Cushion System takes the pain out of every step, to always keep your healthy mobility on track.",
    },
    {
      id: "11",
      name: "OrthoFeet Nira Hands-Free",
      brand_id: "1",
      condition_id: "2",
      style_id: "1",
      gender: "Female",
      price: 165.0,
      rating: 4.07,
      product_url: "https://www.orthofeet.com/products/nira-hands-free-black",
      image_url: "https://www.orthofeet.com/cdn/shop/files/80031-Nira-Green-Blue-Angle.jpg?v=1740149728&width=1200",
      description:
        "Nira takes your active, pain-free comfort to the next level in modern sneaker style. With our patented hands-free technology, you can skip the laces. Just step-in and go! The water-repellant stretch upper keeps pressure off sensitive areas, while an advanced orthotic sole design disperses walking impact, to get you happily through every day's finish line.",
    },
    {
      id: "12",
      name: "OrthoFeet Ace Pickleball Hands-Free",
      brand_id: "1",
      condition_id: "2",
      style_id: "1",
      gender: "Female",
      price: 124.99,
      rating: 4.39,
      product_url: "https://www.orthofeet.com/products/ace-pickleball-hands-free-white-gray",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/88002-Ace-Pickle-Ball-White-Gray-Angle_1242x1674.jpg?v=1729714647",
      description:
        "More game, less pain. Purpose-built for pickleball, Ace dodges joint strain and pressure points with advanced heel-to-toe cushioning, roomy fit and superior body-aligning support. The patented hands-free design slips-on easily and stays secure.",
    },
    {
      id: "13",
      name: "Dr. Comfort Annie X Diabetic shoes",
      brand_id: "2",
      condition_id: "2",
      style_id: "2",
      gender: "Female",
      price: 135.0,
      rating: 4.5,
      product_url: "https://www.amazon.com/Dr-Comfort-Womens-Stretchable-Diabetic/dp/B06XTB7PZT",
      image_url: "https://m.media-amazon.com/images/I/61mJ8tY1HdL._AC_SL1400_.jpg",
      description:
        "Dr. Comfort Annie X Diabetic shoes are the ultimate in comfortable, accommodative diabetics shoes. These shoes are 'Double Depth,' which means that there is enough room for deformities such as hammertoes and bunions.",
    },
    {
      id: "14",
      name: "Brooks Women's Adrenaline GTS 24 Supportive Running Shoe",
      brand_id: "4",
      condition_id: "2",
      style_id: "1",
      gender: "Female",
      price: 145.0,
      rating: 3.9,
      product_url:
        "https://www.brooksrunning.com/en_us/womens/shoes/road-running-shoes/adrenaline-gts-24/1204261B019.080.html",
      image_url:
        "https://www.brooksrunning.com/dw/image/v2/BGPF_PRD/on/demandware.static/-/Sites-brooks-master-catalog/default/dw0ecaf4da/original/120426/120426-019-a-adrenaline-gts-24-women-running-shoes.jpg",
      description:
        "THIS WOMEN'S SHOE IS FOR: The Adrenaline GTS 24 provides support to every stride, now with nitrogen-infused DNA Loft v3 cushioning for even more lightweight, plus responsive comfort.",
    },
    {
      id: "15",
      name: "Orthofeet Edgewater",
      brand_id: "1",
      condition_id: "3",
      style_id: "2",
      gender: "Male",
      price: 145.0,
      rating: 4.3,
      product_url: "https://www.orthofeet.com/products/edgewater-stretch-blue",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/616_Edgewater_Blue_Angle_a7d2b69f-6488-4e48-b644-2b078bb64c55_1242x1674.jpg?v=1702503136",
      description:
        "Orthopedic walking shoes are the most common variety, creating a large market to choose from. Orthofeet hits the intersection of functionality and looks just about as well as any sneaker out there. We like the Edgewater for a cool early-'00s runner shoe look that compliments everything from jeans to joggers.",
    },
    {
      id: "16",
      name: "Teva Women's Original Universal sandals",
      brand_id: "5",
      condition_id: "3",
      style_id: "3",
      gender: "Female",
      price: 60.0,
      rating: 4.6,
      product_url: "https://www.teva.com/women-sandals/original-universal-sandal/8872782024.html",
      image_url:
        "https://dms.deckers.com/tevaus/image/upload/f_auto,q_auto,dpr_auto/b_rgb:f3f3f3/w_966/v1734055584/1003987-BLK_1.png?_s=RAABAB0",
      description:
        "Teva Original sandals feature generous shaping and adjustable straps that accommodate wide feet while remaining lightweight and flexible despite their cushioning.",
    },
    {
      id: "17",
      name: "Teva Men's Original Universal sandals",
      brand_id: "5",
      condition_id: "3",
      style_id: "3",
      gender: "Male",
      price: 60.0,
      rating: 4.5,
      product_url: "https://www.teva.com/men-sandals/original-universal-sandal/8872785999.html",
      image_url:
        "https://dms.deckers.com/tevaus/image/upload/f_auto,q_auto,dpr_auto/b_rgb:f3f3f3/w_966/v1651698098/catalog/images/images/transparent/1004006-BLK_1.png?_s=RAABAB0",
      description:
        "Teva Original sandals feature generous shaping and adjustable straps that accommodate wide feet while remaining lightweight and flexible despite their cushioning.",
    },
    {
      id: "18",
      name: "Classic Clog",
      brand_id: "6",
      condition_id: "3",
      style_id: "3",
      gender: "Unisex",
      price: 49.99,
      rating: 4.7,
      product_url: "https://www.crocs.com/p/classic-clog/10001.html",
      image_url: "https://media.crocs.com/images/t_pdphero/f_auto%2Cq_auto/products/10001_100_ALT140/crocs",
      description:
        "Original. Versatile. Comfortable. It's the iconic clog that started a comfort revolution around the world! The irreverent go-to comfort shoe that you're sure to fall deeper in love with day after day. Crocs Classic Clogs offer lightweight Iconic Crocs Comfort™, a color for every personality, and an ongoing invitation to be comfortable in your own shoes.",
    },
    {
      id: "19",
      name: "Birkenstock Boston Soft Footbed",
      brand_id: "7",
      condition_id: "3",
      style_id: "3",
      gender: "Unisex",
      price: 165.0,
      rating: 4.0,
      product_url:
        "https://www.birkenstock.com/us/boston-soft-footbed-suede-leather/boston-suede-suedeleather-softfootbed-eva-u_46.html",
      image_url:
        "https://www.birkenstock.com/dw/image/v2/BDXC_PRD/on/demandware.static/-/Sites-master-catalog/default/dw4cd34ea4/560771/560771_sole.jpg?sw=848&sh=848&strip=false",
      description:
        "So classic and consistently comfortable, the Boston clog has become a coveted, year-round favorite. Velvety suede lends an effortless feel to the style. Featuring an additional foam layer for cushioning, its soft footbed offers extra comfort plus go-all-day support.",
    },
    {
      id: "20",
      name: "Flux Adapt Runner",
      brand_id: "8",
      condition_id: "3",
      style_id: "1",
      gender: "Unisex",
      price: 139.99,
      rating: 4.7,
      product_url: "https://fluxfootwear.com/collections/running/products/adapt-runner",
      image_url: "https://fluxfootwear.com/cdn/shop/products/ProductPagesPhotosRunning-07_1800x1800.png?v=1683848986",
      description:
        "Crafted for distance, the Adapt Runner features a wide toe box and a zero-drop sole for a natural foot position. It includes a removable, textured insole equipped with over 100 nodes that massage your feet and engage your central nervous system with every step.",
    },
    {
      id: "21",
      name: "OrthoFeet Kita Hands-Free",
      brand_id: "1",
      condition_id: "5",
      style_id: "2",
      gender: "Female",
      price: 125.0,
      rating: 4.26,
      product_url: "https://www.orthofeet.com/products/kita-hands-free-black-black",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/80016-Kita-Black-Black-Angle_68449432-c6bc-44b3-bba7-ad28050d39a3.jpg?v=1702513025&width=1200",
      description:
        "Kita's clean sporty design features our revolutionary hands-free slip-on technology. Tie the laces once, then never bend over to tie them again & just step in, without worrying about them slipping off when walking. From the water-repellant stretchable fabric uppers to the Ortho-Cushion System, Kita changes the game for mobility, support and comfort.",
    },
    {
      id: "22",
      name: "OrthoFeet Ace Pickleball Hands-Free",
      brand_id: "1",
      condition_id: "5",
      style_id: "1",
      gender: "Female",
      price: 124.99,
      rating: 4.39,
      product_url: "https://www.orthofeet.com/products/ace-pickleball-hands-free-white-gray",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/88002-Ace-Pickle-Ball-White-Gray-Angle_1242x1674.jpg?v=1729714647",
      description:
        "More game, less pain. Purpose-built for pickleball, Ace dodges joint strain and pressure points with advanced heel-to-toe cushioning, roomy fit and superior body-aligning support. The patented hands-free design slips-on easily and stays secure.",
    },
    {
      id: "23",
      name: "OrthoFeet Relay",
      brand_id: "1",
      condition_id: "5",
      style_id: "1",
      gender: "Female",
      price: 124.99,
      rating: 4.31,
      product_url: "https://www.orthofeet.com/products/relay",
      image_url: "https://m.media-amazon.com/images/I/61mJ8tY1HdL._AC_SL1400_.jpg",
      description:
        "Get ready for podiatrist-recommended comfort that's born to run. From the lightweight breathable nylon upper to the stable, high traction outsole, Relay keeps your mobility in the lead. Leave pain behind with a heel-to-toe max cushioned sole and a near custom fit, while the Ortho-Cushion System offloads pressure and aligns ergonomic support for every stride.",
    },
    {
      id: "24",
      name: "Vionic Rejuvenate Unisex Slide Recovery Sandals",
      brand_id: "9",
      condition_id: "5",
      style_id: "3",
      gender: "Unisex",
      price: 85.0,
      rating: 4.0,
      product_url: "https://orthoticshop.com/vionic-rejuvenate-unisex-slide-recovery-sandals.html",
      image_url:
        "https://cdn11.bigcommerce.com/s-nc8qsb7kb9/images/stencil/1280x1280/products/4851/96619/REJUVENATE-I0899S1001-BLACKBLACK-2pa-med__47967.1729822157.jpg?c=1",
      description:
        "Show your feet some love in this recovery slide featuring adjustable nubuck straps, textured footbeds and dual-density cushioning. Vionic's softest three-zone comfort experience.",
    },
    {
      id: "25",
      name: "Orthofeet Edgewater",
      brand_id: "1",
      condition_id: "5",
      style_id: "2",
      gender: "Male",
      price: 150.0,
      rating: 4.3,
      product_url: "https://www.orthofeet.com/products/edgewater-stretch-blue",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/616_Edgewater_Blue_Angle_a7d2b69f-6488-4e48-b644-2b078bb64c55_1242x1674.jpg?v=1702503136",
      description:
        "Orthopedic walking shoes are the most common variety, creating a large market to choose from. Orthofeet hits the intersection of functionality and looks just about as well as any sneaker out there.",
    },
    {
      id: "26",
      name: "Propét Men's Finn Plain Toe Shoe",
      brand_id: "10",
      condition_id: "5",
      style_id: "4",
      gender: "Male",
      price: 90.0,
      rating: 4.0,
      product_url: "https://www.amazon.com/Propet-Mens-Oxford-Black-XX-Wide/dp/B0B6GQJS6N",
      image_url: "https://m.media-amazon.com/images/I/81VB+roWPaL._AC_SX695_.jpg",
      description:
        "Propét creates a wide range of orthopedic shoes that you would never guess are orthopedic from the looks. This is a great work shoe or formal shoe with orthopedic level comfort.",
    },
    {
      id: "27",
      name: "Vionic Relax II Women's Orthotic Slide Slippers",
      brand_id: "9",
      condition_id: "5",
      style_id: "3",
      gender: "Female",
      price: 80.0,
      rating: 4.5,
      product_url: "https://orthoticshop.com/vionic-relax-ii-orthotic-slippers.html",
      image_url:
        "https://cdn11.bigcommerce.com/s-nc8qsb7kb9/images/stencil/1280x1280/products/6221/110460/RELAX%20II-J0895F4652-LIGHT%20PINK-1th-med__71768.1721797140.jpg?c=1",
      description:
        "Discover Ultimate Comfort with Vionic Relax II Women's Orthotic Slide Slippers. Step into a world of comfort and support with luxurious materials and advanced features.",
    },
    {
      id: "28",
      name: "OrthoFeet Tilos Hands-Free",
      brand_id: "1",
      condition_id: "5",
      style_id: "2",
      gender: "Male",
      price: 160.0,
      rating: 4.25,
      product_url: "https://www.orthofeet.com/products/tilos-hands-free-black-black",
      image_url: "https://www.orthofeet.com/cdn/shop/files/20022-Tilos-Navy-Blue-Angle.jpg?v=1733432571&width=1200",
      description:
        "It's ready, set, go & for all day comfort in modern sneaker style. Our patented hands-free, slip-on technology means no time bent over to tie the laces. Water-repellent stretch uppers take the pressure off every curve and bump of your feet, while the advanced, customizable Ortho-Cushion System takes the pain out of every step, to always keep your healthy mobility on track.",
    },
    {
      id: "29",
      name: "OrthoFeet Kita Hands-Free",
      brand_id: "1",
      condition_id: "4",
      style_id: "2",
      gender: "Female",
      price: 125.0,
      rating: 4.26,
      product_url: "https://www.orthofeet.com/products/kita-hands-free-black-black",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/80016-Kita-Black-Black-Angle_68449432-c6bc-44b3-bba7-ad28050d39a3.jpg?v=1702513025&width=1200",
      description:
        "Kita's clean sporty design features our revolutionary hands-free slip-on technology. Tie the laces once, then never bend over to tie them again & just step in, without worrying about them slipping off when walking. From the water-repellant stretchable fabric uppers to the Ortho-Cushion System, Kita changes the game for mobility, support and comfort.",
    },
    {
      id: "30",
      name: "OrthoFeet Fairway Hands-Free Golf",
      brand_id: "1",
      condition_id: "4",
      style_id: "1",
      gender: "Male",
      price: 129.99,
      rating: 4.39,
      product_url: "https://www.orthofeet.com/products/fairway-hands-free-blue-white-gray",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/28003-Fairway-HF-Golf-White-Blue-Gray-Angle_1242x1674.jpg?v=1737477136",
      description:
        "Put your comfort to the fore and enjoy every round more with advanced support, heel-to-toe impact absorption and the easy walking stability of the Ortho-Cushion System. Our patented hands-free design offers slip-on ease and secure footing, with a golf-spike tread for traction on uneven surfaces.",
    },
    {
      id: "31",
      name: "OrthoFeet Nira Hands-Free",
      brand_id: "1",
      condition_id: "4",
      style_id: "1",
      gender: "Female",
      price: 165.0,
      rating: 4.07,
      product_url: "https://www.orthofeet.com/products/nira-hands-free-black",
      image_url: "https://www.orthofeet.com/cdn/shop/files/80031-Nira-Green-Blue-Angle.jpg?v=1740149728&width=1200",
      description:
        "Nira takes your active, pain-free comfort to the next level in modern sneaker style. With our patented hands-free technology, you can skip the laces. Just step-in and go! The water-repellant stretch upper keeps pressure off sensitive areas, while an advanced orthotic sole design disperses walking impact, to get you happily through every day's finish line.",
    },
    {
      id: "32",
      name: "Apt. 9 Denver Men's Dress Shoes",
      brand_id: "12",
      condition_id: "4",
      style_id: "4",
      gender: "Male",
      price: 50.0,
      rating: 4.4,
      product_url: "https://www.kohls.com/product/prd-5155432/apt-9-denver-mens-dress-shoes.jsp",
      image_url: "https://media.kohlsimg.com/is/image/kohls/5155432_Black?wid=805&hei=805&op_sharpen=1",
      description:
        "SHOE FEATURES Ortholite technology enables air flow for a cool foot, wicks away moisture, inhibits odor and fungus and provides long lasting cushioning. Flexible, traction outsole.",
    },
    {
      id: "33",
      name: "OrthoFeet Clara",
      brand_id: "1",
      condition_id: "4",
      style_id: "3",
      gender: "Female",
      price: 97.5,
      rating: 4.41,
      product_url: "https://www.orthofeet.com/products/clara-oatmeal-plaid",
      image_url:
        "https://www.orthofeet.com/cdn/shop/files/71202-Clara-Oatmeal-Plaid-Wool-Angle_1242x1674.jpg?v=1727970533",
      description:
        "Move easy, with all the comforts of home, even when you venture out. Slip into the faux fur lining (even the insole) for extra cozy protection. And take the pressure out of your steps with this ergonomic footwear designed to alleviate common foot pain.",
    },
    {
      id: "34",
      name: "Time and Tru Women's Ballet Block Heel Pumps",
      brand_id: "11",
      condition_id: "4",
      style_id: "4",
      gender: "Female",
      price: 20.0,
      rating: 4.4,
      product_url: "https://www.walmart.com/ip/Time-and-Tru-Women-s-Ballet-Heels-Sizes-6-11/5340958555",
      image_url:
        "https://i5.walmartimages.com/seo/Time-and-Tru-Women-s-Ballet-Heels-Sizes-6-11_f1c5dbdb-c271-4fe4-bbb9-94ac44e3669c.9c493e7a00992c7c84010e893c3e0f5d.jpeg",
      description:
        "Step into plié-worthy style with these Ballet Block Heel Pumps from Time and Tru. These ballet heels add the perfect touch of vintage-inspired charm to any look. Features Memory Foam cushioning for comfort.",
    },
  ],
  shoe_conditions: [
    { shoe_id: "1", condition_id: "1" },
    { shoe_id: "2", condition_id: "1" },
    { shoe_id: "3", condition_id: "1" },
    { shoe_id: "4", condition_id: "1" },
    { shoe_id: "5", condition_id: "1" },
    { shoe_id: "6", condition_id: "1" },
    { shoe_id: "7", condition_id: "2" },
    { shoe_id: "8", condition_id: "2" },
    { shoe_id: "9", condition_id: "2" },
    { shoe_id: "10", condition_id: "2" },
    { shoe_id: "11", condition_id: "2" },
    { shoe_id: "12", condition_id: "2" },
    { shoe_id: "13", condition_id: "2" },
    { shoe_id: "14", condition_id: "2" },
    { shoe_id: "15", condition_id: "3" },
    { shoe_id: "16", condition_id: "3" },
    { shoe_id: "17", condition_id: "3" },
    { shoe_id: "18", condition_id: "3" },
    { shoe_id: "19", condition_id: "3" },
    { shoe_id: "20", condition_id: "3" },
    { shoe_id: "21", condition_id: "5" },
    { shoe_id: "22", condition_id: "5" },
    { shoe_id: "23", condition_id: "5" },
    { shoe_id: "24", condition_id: "5" },
    { shoe_id: "25", condition_id: "5" },
    { shoe_id: "26", condition_id: "5" },
    { shoe_id: "27", condition_id: "5" },
    { shoe_id: "28", condition_id: "5" },
    { shoe_id: "29", condition_id: "4" },
    { shoe_id: "30", condition_id: "4" },
    { shoe_id: "31", condition_id: "4" },
    { shoe_id: "32", condition_id: "4" },
    { shoe_id: "33", condition_id: "4" },
    { shoe_id: "34", condition_id: "4" },
  ],
  shoe_images: [
    {
      id: "1",
      shoe_id: "1",
      url: "https://www.orthofeet.com/cdn/shop/files/20022-Tilos-Navy-Blue-Angle.jpg?v=1733432571&width=1200",
    },
    {
      id: "2",
      shoe_id: "2",
      url: "https://www.orthofeet.com/cdn/shop/files/80016-Kita-Black-Black-Angle_68449432-c6bc-44b3-bba7-ad28050d39a3.jpg?v=1702513025&width=1200",
    },
    {
      id: "3",
      shoe_id: "3",
      url: "https://www.orthofeet.com/cdn/shop/files/28003-Fairway-HF-Golf-White-Blue-Gray-Angle_1242x1674.jpg?v=1737477136",
    },
    {
      id: "4",
      shoe_id: "4",
      url: "https://www.orthofeet.com/cdn/shop/files/88002-Ace-Pickle-Ball-White-Gray-Angle_1242x1674.jpg?v=1729714647",
    },
    {
      id: "5",
      shoe_id: "5",
      url: "https://www.orthofeet.com/cdn/shop/files/80031-Nira-Green-Blue-Angle.jpg?v=1740149728&width=1200",
    },
    { id: "6", shoe_id: "6", url: "https://m.media-amazon.com/images/I/61mJ8tY1HdL._AC_SL1400_.jpg" },
    { id: "7", shoe_id: "7", url: "https://m.media-amazon.com/images/I/71rZ2dHT-mL._AC_SY695_.jpg" },
    {
      id: "8",
      shoe_id: "8",
      url: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwc6c2d4f1/images/large/124637_NVW.jpg?sw=1600",
    },
    {
      id: "9",
      shoe_id: "9",
      url: "https://www.drcomfort.com/media/catalog/product/cache/2f72bf07d911f86e77d93eed57c55d3a/r/e/refresh-x-blue-2950-3-4_47.jpg",
    },
    {
      id: "10",
      shoe_id: "10",
      url: "https://www.orthofeet.com/cdn/shop/files/20022-Tilos-Navy-Blue-Angle.jpg?v=1733432571&width=1200",
    },
    {
      id: "11",
      shoe_id: "11",
      url: "https://www.orthofeet.com/cdn/shop/files/80031-Nira-Green-Blue-Angle.jpg?v=1740149728&width=1200",
    },
    {
      id: "12",
      shoe_id: "12",
      url: "https://www.orthofeet.com/cdn/shop/files/88002-Ace-Pickle-Ball-White-Gray-Angle_1242x1674.jpg?v=1729714647",
    },
    { id: "13", shoe_id: "13", url: "https://m.media-amazon.com/images/I/61mJ8tY1HdL._AC_SL1400_.jpg" },
    {
      id: "14",
      shoe_id: "14",
      url: "https://www.brooksrunning.com/dw/image/v2/BGPF_PRD/on/demandware.static/-/Sites-brooks-master-catalog/default/dw0ecaf4da/original/120426/120426-019-a-adrenaline-gts-24-women-running-shoes.jpg",
    },
    {
      id: "15",
      shoe_id: "15",
      url: "https://www.orthofeet.com/cdn/shop/files/616_Edgewater_Blue_Angle_a7d2b69f-6488-4e48-b644-2b078bb64c55_1242x1674.jpg?v=1702503136",
    },
    {
      id: "16",
      shoe_id: "16",
      url: "https://dms.deckers.com/tevaus/image/upload/f_auto,q_auto,dpr_auto/b_rgb:f3f3f3/w_966/v1734055584/1003987-BLK_1.png?_s=RAABAB0",
    },
    {
      id: "17",
      shoe_id: "17",
      url: "https://dms.deckers.com/tevaus/image/upload/f_auto,q_auto,dpr_auto/b_rgb:f3f3f3/w_966/v1651698098/catalog/images/images/transparent/1004006-BLK_1.png?_s=RAABAB0",
    },
    {
      id: "18",
      shoe_id: "18",
      url: "https://media.crocs.com/images/t_pdphero/f_auto%2Cq_auto/products/10001_100_ALT140/crocs",
    },
    {
      id: "19",
      shoe_id: "19",
      url: "https://www.birkenstock.com/dw/image/v2/BDXC_PRD/on/demandware.static/-/Sites-master-catalog/default/dw4cd34ea4/560771/560771_sole.jpg?sw=848&sh=848&strip=false",
    },
    {
      id: "20",
      shoe_id: "20",
      url: "https://fluxfootwear.com/cdn/shop/products/ProductPagesPhotosRunning-07_1800x1800.png?v=1683848986",
    },
    {
      id: "21",
      shoe_id: "21",
      url: "https://www.orthofeet.com/cdn/shop/files/80016-Kita-Black-Black-Angle_68449432-c6bc-44b3-bba7-ad28050d39a3.jpg?v=1702513025&width=1200",
    },
    {
      id: "22",
      shoe_id: "22",
      url: "https://www.orthofeet.com/cdn/shop/files/88002-Ace-Pickle-Ball-White-Gray-Angle_1242x1674.jpg?v=1729714647",
    },
    { id: "23", shoe_id: "23", url: "https://m.media-amazon.com/images/I/61mJ8tY1HdL._AC_SL1400_.jpg" },
    {
      id: "24",
      shoe_id: "24",
      url: "https://cdn11.bigcommerce.com/s-nc8qsb7kb9/images/stencil/1280x1280/products/4851/96619/REJUVENATE-I0899S1001-BLACKBLACK-2pa-med__47967.1729822157.jpg?c=1",
    },
    {
      id: "25",
      shoe_id: "25",
      url: "https://www.orthofeet.com/cdn/shop/files/616_Edgewater_Blue_Angle_a7d2b69f-6488-4e48-b644-2b078bb64c55_1242x1674.jpg?v=1702503136",
    },
    { id: "26", shoe_id: "26", url: "https://m.media-amazon.com/images/I/81VB+roWPaL._AC_SX695_.jpg" },
    {
      id: "27",
      shoe_id: "27",
      url: "https://cdn11.bigcommerce.com/s-nc8qsb7kb9/images/stencil/1280x1280/products/6221/110460/RELAX%20II-J0895F4652-LIGHT%20PINK-1th-med__71768.1721797140.jpg?c=1",
    },
    {
      id: "28",
      shoe_id: "28",
      url: "https://www.orthofeet.com/cdn/shop/files/20022-Tilos-Navy-Blue-Angle.jpg?v=1733432571&width=1200",
    },
    {
      id: "29",
      shoe_id: "29",
      url: "https://www.orthofeet.com/cdn/shop/files/80016-Kita-Black-Black-Angle_68449432-c6bc-44b3-bba7-ad28050d39a3.jpg?v=1702513025&width=1200",
    },
    {
      id: "30",
      shoe_id: "30",
      url: "https://www.orthofeet.com/cdn/shop/files/28003-Fairway-HF-Golf-White-Blue-Gray-Angle_1242x1674.jpg?v=1737477136",
    },
    {
      id: "31",
      shoe_id: "31",
      url: "https://www.orthofeet.com/cdn/shop/files/80031-Nira-Green-Blue-Angle.jpg?v=1740149728&width=1200",
    },
    {
      id: "32",
      shoe_id: "32",
      url: "https://media.kohlsimg.com/is/image/kohls/5155432_Black?wid=805&hei=805&op_sharpen=1",
    },
    {
      id: "33",
      shoe_id: "33",
      url: "https://www.orthofeet.com/cdn/shop/files/71202-Clara-Oatmeal-Plaid-Wool-Angle_1242x1674.jpg?v=1727970533",
    },
    {
      id: "34",
      shoe_id: "34",
      url: "https://i5.walmartimages.com/seo/Time-and-Tru-Women-s-Ballet-Heels-Sizes-6-11_f1c5dbdb-c271-4fe4-bbb9-94ac44e3669c.9c493e7a00992c7c84010e893c3e0f5d.jpeg",
    },
  ],
}

